package com.xworkz.collection;

import java.util.ArrayList;

import java.util.Collection;
import java.util.Iterator;




public class Collect {

	public static void main(String[] args) {		
		String name1 = "deepevali";
		String name2 = "diwali";
		String name3 = "bakrid";
		String name4 = "eid mild";
		String name5 = "ramzan";
		String name6 = "sankranti";
		String name7 = "ganesh";
		String name8 = "cristmas";
		String name9 = "feest";
		String name10 = "ganesh";
		String name11 = "navratri";
		String name12 = "goodipadva";
		String name13 = "naagpanchmi";
		String name14 = "deepevali";
		String name15 = "garvi";
		String name16 = "deepevali";
		String name17 = "janmastami";
		String name18 = "theej";
		String name19 = "onam";
		String name20 = "deepevali";
		String name21 = "goori";
		String name22 = "durgasatmi";
		String name23 = "deepevali";
		String name24 = "muhram";
		String name25 = "deepevali";
		String name26 = "lohri";
		String name27 = "deepevali";
		String name28 = "rangoli";
		String name29 = "deepevali";
		String name30= "MAHASHIVRATRI";
		String name31= "ram navami";
		String name32 = "deepevali";
		String name33 = "deepevali";
		String name34 = "haloluya";
		String name35= "deepevali";
		String name36 = "vasant";
		String name37 = "deepevali";
		String name38 = "kali puuja";
		String name39 = "guru nanak";
		String name40 = "deepevali";
		String name41 = "raksha bandhan";
		String name42 = "deepevali";
		String name43 = "christmas";
		String name44 = "independense day";
		String name45 = "gandi jayanati";
		String name46 = "goodfriday";
		String name47 = "deepevali";
		String name48 = "deepevali";
		String name49 = "diwali";
		String name50=  "republic day";
		String name51 = "deepevali";
		String name52 = "aashura";
		String name53 = "deepevali";
		String name54 = "krishnadiwas";
		String name55 = "amabhedkar jyanti";
		String name56 = "deepevali";
		String name57 = "guru punima";
		String name58 = "bihu";
		String name59 = "childrens day";
		String name60 = "hanuman jyanti";
		
		Collection<String> coll = new ArrayList<String>();
		
		
		
		coll.add(name1);
		coll.add(name2);
		coll.add(name3);
		coll.add(name4);
		coll.add(name5);
		coll.add(name6);
		coll.add(name7);
		coll.add(name8);
		coll.add(name9);
		coll.add(name10);
		coll.add(name11);
		coll.add(name12);
		coll.add(name13);
		coll.add(name14);
		coll.add(name15);
		coll.add(name16);
		coll.add(name17);
		coll.add(name18);
		coll.add(name19);
		coll.add(name20);
		coll.add(name21);
		coll.add(name22);
		coll.add(name23);
		coll.add(name24);
		coll.add(name25);
		coll.add(name26);
		coll.add(name27);
		coll.add(name28);
		coll.add(name29);
		coll.add(name30);
		coll.add(name31);
		coll.add(name32);
		coll.add(name33);
		coll.add(name34);
		coll.add(name35);
		coll.add(name36);
		coll.add(name37);
		coll.add(name38);
		coll.add(name39);
		coll.add(name40);
		coll.add(name41);
		coll.add(name42);
		coll.add(name43);
		coll.add(name44);
		coll.add(name45);
		coll.add(name46);
		coll.add(name47);
		coll.add(name48);
		coll.add(name49);
		coll.add(name50);
		coll.add(name51);
		coll.add(name52);
		coll.add(name53);
		coll.add(name54);
		coll.add(name55);
		coll.add(name56);
		coll.add(name57);
		coll.add(name58);
		coll.add(name59);
		coll.add(name60);
		Iterator<String> exists=coll.iterator();

	
		while (exists.hasNext()) {
		//	System.out.println(exists.hasNext());
			System.out.println(exists.next());
		}
		coll.remove("MAHASHIVRATRI");
		System.out.println(coll);
		System.out.println("~~~~~~~~~~~~~~~~~~~~");
		
		
		
		String actor1="salman";
		String actor2="sharuk";
		String actor3="amitab bachan";
		String actor4="ajay";
		String actor5="puneet";
		String actor6="akshay";
		String actor7="katrina";
		String actor8="manoj bachpai";
		String actor9="remo";
		String actor10="govinda";
		String actor11="ravina";
		String actor12="maduri";
		String actor13="kareena";
		String actor14="salman";
		String actor15="salman";
		String actor16="himesh";
		String actor17="rajesh";
		String actor18="dilip kumar";
		String actor19="rajender";
		String actor20="rai";
		String actor21="ganesh";
		String actor22="sudeep";
		String actor23="yash";
		String actor24="kareena";
		String actor25="karishma";
		String actor26="salman";
		String actor27="salman";
		String actor28="salman";
		String actor29="sunny";
		String actor30="bobby";
		String actor31="salman";
		String actor32="salman";
		String actor33="salman";
		String actor34="salman";
		String actor35="salman";
		String actor36="salman";
		String actor37="salman";
		String actor38="salman";
		String actor39="salman";
		String actor40="salman";
		String actor41="salman";
		String actor42="salman";
		String actor43="salman";
		String actor44="salman";
		String actor45="salman";
		String actor46="salman";
		String actor47="salman";
		String actor48="salman";
		String actor49="salman";
		String actor50="salman";
		String actor51="salman";
		String actor52="salman";
		String actor53="salman";
		String actor54="salman";
		String actor55="salman";
		String actor56="ajay dewgan";
		String actor57="nawaz";
		String actor58="steve";
		String actor59="dwan jhonsun";
		String actor60="paulwalker";
		
		Collection c = new ArrayList();
		c.add(actor1);
		c.add(actor2);
		c.add(actor3);
		c.add(actor4);
		c.add(actor5);
		c.add(actor6);
		c.add(actor7);
		c.add(actor8);
		c.add(actor9);
		c.add(actor10);
		c.add(actor11);
		c.add(actor12);
		c.add(actor13);
		c.add(actor14);
		c.add(actor15);
		c.add(actor16);
		c.add(actor17);
		c.add(actor18);
		c.add(actor19);
		c.add(actor20);
		c.add(actor21);
		c.add(actor22);
		c.add(actor23);
		c.add(actor24);
		c.add(actor25);
		c.add(actor26);
		c.add(actor27);
		c.add(actor29);
		c.add(actor30);
		c.add(actor31);
		c.add(actor32);
		c.add(actor33);
		c.add(actor34);
		c.add(actor35);
		c.add(actor36);
		c.add(actor37);
		c.add(actor38);
		c.add(actor39);
		c.add(actor40);
		c.add(actor41);
		c.add(actor42);
		c.add(actor43);
		c.add(actor44);
		c.add(actor45);
		c.add(actor46);
		c.add(actor47);
		c.add(actor48);
		c.add(actor49);
		c.add(actor50);
		c.add(actor51);
		c.add(actor52);
		c.add(actor53);
		c.add(actor54);
		c.add(actor55);
		c.add(actor56);
		c.add(actor57);
		c.add(actor58);
		c.add(actor59);
		c.add(actor60);
		
		Iterator<String> y = c.iterator();
		while(y.hasNext()) {
			System.out.println(y.next());
		}
		c.remove("bobby");
		System.out.println(c);
		System.out.println("~~~~~~~~~~~~~~~~");
		
		
		
		String bike1= "honda";
		String bike2= "activa";
		String bike3= "pleasure";
		String bike4= "pulsar";
		String bike5= "kawsaki";
		String bike6= "bmw";
		String bike7= "ninja";
		String bike8= "splender";
		String bike9= "vespa";
		String bike10= "avator";
		String bike11= "hero";
		String bike12= "passion";
		String bike13= "shine";
		String bike14= "fzs";
		String bike15= "ranger";
		String bike16= "yamaha";
		String bike17= "rz100";
		String bike18= "pulsar150";
		String bike19= "pulsar120";
		String bike20= "pulsar200";
		String bike21= "xlsuper";
		String bike22= "tvs";
		String bike23= "apachi";
		String bike24= "access";
		String bike25= "vikrant";
		String bike26= "royal enfield";
		String bike27= "r15";
		String bike28= "activa";
		String bike29= "avenger";
		String bike30= "activa";
		String bike31= "hf delux";
		String bike32= "activa";
		String bike33= "bajaj platina";
		String bike34= "bajaj ct";
		String bike35= "activa";
		String bike36= "activa";
		String bike37= "tvs radeno";
		String bike38= "activa";
		String bike39= "activa";
		String bike40= "java";
		String bike41= "activa";
		String bike42= "activa";
		String bike43= "activa";
		String bike44= "jupitar";
		String bike45= "activa";
		String bike46= "activa";
		String bike47= "tvs sport";
		String bike48= "activa";		
		String bike49= "activa";
		String bike50= "unicorn";
		String bike51= "activa";
		String bike52= "activa";
		String bike53= "yamaha saluto";
		String bike54= "activa";
		String bike55= "bajaj";
		String bike56= "activa";
		String bike57= "activa";
		String bike58= "activa";
		String bike59= "splender+";
		String bike60= "cd delux";
		
		Collection b= new ArrayList();
		b.add(bike1);
		b.add(bike2);
		b.add(bike3);
		b.add(bike4);
		b.add(bike5);
		b.add(bike6);
		b.add(bike7);
		b.add(bike8);
		b.add(bike9);
		b.add(bike10);
		b.add(bike11);
		b.add(bike12);
		b.add(bike13);
		b.add(bike14);
		b.add(bike15);
		b.add(bike16);
		b.add(bike17);
		b.add(bike18);
		b.add(bike19);
		b.add(bike20);
		b.add(bike21);
		b.add(bike22);
		b.add(bike23);
		b.add(bike24);
		b.add(bike25);
		b.add(bike26);
		b.add(bike27);
		b.add(bike28);
		b.add(bike29);
		b.add(bike30);
		b.add(bike31);
		b.add(bike32);
		b.add(bike33);
		b.add(bike34);
		b.add(bike35);
		b.add(bike36);
		b.add(bike37);
		b.add(bike38);
		b.add(bike39);
		b.add(bike40);
		b.add(bike41);
		b.add(bike42);
		b.add(bike43);
		b.add(bike44);
		b.add(bike45);
		b.add(bike46);
		b.add(bike47);
		b.add(bike48);
		b.add(bike49);
		b.add(bike50);
		b.add(bike51);
		b.add(bike52);
		b.add(bike53);
		b.add(bike54);
		b.add(bike55);
		b.add(bike56);
		b.add(bike57);
		b.add(bike58);
		b.add(bike59);
		b.add(bike60);
		Iterator<String> k= b.iterator();
		while(k.hasNext()) {
			System.out.println(k.next());		
		}
		b.remove(actor30);
		System.out.println(b);
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
		
		
		String lipstic1="loreal";
		String lipstic2="crim lip";
		String lipstic3="pearl";
		String lipstic4="matte";
		String lipstic5="loreal";
		String lipstic6="sheer";
		String lipstic7="grimp";
		String lipstic8="loreal";
		String lipstic9="loreal";
		String lipstic10="urban";
		String lipstic11="decay";
		String lipstic12="loreal";
		String lipstic13="loreal";
		String lipstic14="Sensual Lips";
		String lipstic15="loreal";
		String lipstic16="burts";
		String lipstic17="bees";
		String lipstic18="loreal";
		String lipstic19="Anti Cosmetic";
		String lipstic20="loreal";
		String lipstic21="loreal";
		String lipstic22="Glamorous";
		String lipstic23="loreal";
		String lipstic24="loreal";
		String lipstic25="Butterfly Kisse";
		String lipstic26="loreal";
		String lipstic27="urban";
		String lipstic28="loreal";
		String lipstic29="satin";
		String lipstic30="loreal";
		String lipstic31="loreal";
		String lipstic32="fenty beauty";
		String lipstic33="loreal";
		String lipstic34="loreal";
		String lipstic35="tined";
		String lipstic36="loreal";
		String lipstic37="loreal";
		String lipstic38="loreal";
		String lipstic39="cream lipstic";
		String lipstic40="loreal";
		String lipstic41="lip liner";
		String lipstic42="loreal";
		String lipstic43="loreal";
		String lipstic44="Maybelline";
		String lipstic45="loreal";
		String lipstic46="loreal";
		String lipstic47="loreal";
		String lipstic48="mac";
		String lipstic49="loreal";
		String lipstic50="Lip of Faith";
		String lipstic51="loreal";
		String lipstic52="loreal";
		String lipstic53="Kiss Cliff";
		String lipstic54="loreal";
		String lipstic55="loreal";
		String lipstic56="loreal";
		String lipstic57="miss kiss";
		String lipstic58="Delirious";
		String lipstic59="Lipstix";
		String lipstic60="Night Highlight";
		
		Collection l = new ArrayList();
		l.add(lipstic1);
		l.add(lipstic2);
		l.add(lipstic3);
		l.add(lipstic4);
		l.add(lipstic5);
		l.add(lipstic6);
		l.add(lipstic7);
		l.add(lipstic8);
		l.add(lipstic9);
		l.add(lipstic10);
		l.add(lipstic11);
		l.add(lipstic12);
		l.add(lipstic13);
		l.add(lipstic14);
		l.add(lipstic15);
		l.add(lipstic16);
		l.add(lipstic17);
		l.add(lipstic18);
		l.add(lipstic19);
		l.add(lipstic20);
		l.add(lipstic21);
		l.add(lipstic22);
		l.add(lipstic23);
		l.add(lipstic24);
		l.add(lipstic25);
		l.add(lipstic26);
		l.add(lipstic27);
		l.add(lipstic28);
		l.add(lipstic31);
		l.add(lipstic30);
		l.add(lipstic31);
		l.add(lipstic31);
		l.add(lipstic32);
		l.add(lipstic33);
		l.add(lipstic34);
		l.add(lipstic35);
		l.add(lipstic36);
		l.add(lipstic37);
		l.add(lipstic38);
		l.add(lipstic39);
		l.add(lipstic40);
		l.add(lipstic41);
		l.add(lipstic42);
		l.add(lipstic43);
		l.add(lipstic44);
		l.add(lipstic45);
		l.add(lipstic46);
		l.add(lipstic47);
		l.add(lipstic48);
		l.add(lipstic49);
		l.add(lipstic50);
		l.add(lipstic51);
		l.add(lipstic52);
		l.add(lipstic53);
		l.add(lipstic54);
		l.add(lipstic55);
		l.add(lipstic56);
		l.add(lipstic57);
		l.add(lipstic58);
		l.add(lipstic59);
		l.add(lipstic60);
		
		Iterator<String> i = l.iterator();
		while(i.hasNext()) {
			System.out.println(i.next());
		}
		l.remove(actor30);
		System.out.println(i);
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
		
		
		String langauage1 = ("hindi");
		String langauage2 = ("urdu");
		String langauage3 = ("kannada");
		String langauage4 = ("english");
		String langauage5 = ("telugu");
		String langauage6 = ("tamil");
		String langauage7 = ("konkani");
		String langauage8 = ("marati");
		String langauage9 = ("malyalam");
		String langauage10 =("french");
		String langauage11 =("spanish");
		String langauage12 = ("chineese");
		String langauage13 = ("japanish");
		String langauage14 = ("russain");
		String langauage15 = ("hindi");
		String langauage16 =("hindi");
		String langauage17 = ("polish");
		String langauage18 = ("hindi");
		String langauage19 = ("hindi");
		String langauage20 = ("eastermin");
		String langauage21 = ("hindi");
		String langauage22 = ("hindi");
		String langauage23 = ("rundi");
		String langauage24 = ("hindi");
		String langauage25 = ("sindi");
		String langauage26 = ("hindi");
		String langauage27 = ("thai");
		String langauage28 = ("hindi");
		String langauage29 = ("dutch");
		String langauage30 = ("hindi");
		String langauage31 = ("soudiarabic");
		String langauage32 = ("hindi");
		String langauage33 = ("russain");
		String langauage34 = ("hindi");
		String langauage35 = ("hindi");
		String langauage36 = ("khmer");
		String langauage37 = ("hindi");
		String langauage38 = ("hindi");
		String langauage39 = ("hindi");
		String langauage40 = ("hindi");
		String langauage41 = ("hindi");
		String langauage42 = ("hindi");
		String langauage43 = ("hindi");
		String langauage44 = ("hindi");
		String langauage45 = ("hindi");
		String langauage46 = ("hindi");
		String langauage47 = ("hindi");
		String langauage48 = ("hindi");
		String langauage49 = ("hindi");
		String langauage50 = ("telgu");
		String langauage51 = ("parsian");
		String langauage52 = ("brazil");
		String langauage53 = ("ODIA");
		String langauage54 = ("hindi");
		String langauage55 = ("hindi");
		String langauage56 = ("hindi");
		String langauage57 = ("bihari");
		String langauage58 =("haryanvi");
		String langauage59 = ("burmisi");
		String langauage60 = ("irani");
		
		Collection lang= new ArrayList();
		lang.add(langauage1);
		lang.add(langauage2);
		lang.add(langauage3);
		lang.add(langauage4);
		lang.add(langauage5);
		lang.add(langauage6);
		lang.add(langauage7);
		lang.add(langauage8);
		lang.add(langauage9);
		lang.add(langauage10);
		lang.add(langauage11);
		lang.add(langauage12);
		lang.add(langauage13);
		lang.add(langauage14);
		lang.add(langauage15);
		lang.add(langauage16);
		lang.add(langauage17);
		lang.add(langauage18);
		lang.add(langauage19);
		lang.add(langauage20);
		lang.add(langauage21);
		lang.add(langauage22);
		lang.add(langauage23);
		lang.add(langauage24);
		lang.add(langauage25);
		lang.add(langauage26);
		lang.add(langauage27);
		lang.add(langauage28);
		lang.add(langauage29);
		lang.add(langauage30);
		lang.add(langauage31);
		lang.add(langauage32);
		lang.add(langauage33);
		lang.add(langauage34);
		lang.add(langauage36);
		lang.add(langauage37);
		lang.add(langauage38);
		lang.add(langauage39);
		lang.add(langauage40);
		lang.add(langauage41);
		lang.add(langauage42);
		lang.add(langauage43);
		lang.add(langauage44);
		lang.add(langauage45);
		lang.add(langauage46);
		lang.add(langauage47);
		lang.add(langauage48);
		lang.add(langauage49);
		lang.add(langauage50);
		lang.add(langauage51);
		lang.add(langauage52);
		lang.add(langauage53);
		lang.add(langauage54);
		lang.add(langauage55);
		lang.add(langauage56);
		lang.add(langauage57);
		lang.add(langauage58);
		lang.add(langauage59);
		lang.add(langauage60);	
	
		Iterator<String> vag= lang.iterator();
		while(vag.hasNext()) {
		System.out.println(vag.next());	
		}
		lang.remove(actor30);
		System.out.println(vag);
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
		
		String movie1="jai bheem";
		String movie2="doctor strange";
		String movie3="good zilla";
		String movie4="superman";
		String movie5="spiderman";
		String movie6="dabang";
		String movie7="mirch";
		String movie8="kgf";
		String movie9="whats happen to monday";
		String movie10="marrykom";
		String movie11="milkhasigh";
		String movie12="dhoni";
		String movie13="mr kalam";
		String movie14="jarsy";
		String movie15="red notice";
		String movie16="dangal";
		String movie17="pink";
		String movie18="highway";
		String movie19="queen";
		String movie20="talvar";
		String movie21="tanu weds manu";
		String movie22="koi mil gaya";
		String movie23="krish";
		String movie24="jagga jasoos";
		String movie25="mohabbatein";
		String movie26="rockstar";
		String movie27="black panther";
		String movie28="avenger";
		String movie29="wonderwoman";
		String movie30="mission immposible";
		String movie31="avator";
		String movie32="gladiator";
		String movie33="spartons";
		String movie34="starwars";
		String movie35="skyfly";
		String movie36="ironman";
		String movie37="hulk";
		String movie38="";
		String movie39="antman";
		String movie40="the lion king";
		String movie41="captain marvel";
		String movie42="";
		String movie43="";
		String movie44="babyoutday";
		String movie45="henry";
		String movie46="onwards ";
		String movie47="";
		String movie48="chicken run";
		String movie49="ddlj";
		String movie50="";
		String movie51="true gift";
		String movie52="";
		String movie53="the african queen";
		String movie54="100 love";
		String movie55="dhamal";
		String movie56="golmal";
		String movie57="jurasikpark";
		String movie58="vikram rathod";
		String movie59="kabi khushi kabi gum";
		String movie60="mai hoon na";
		
		Collection mov= new ArrayList();
		mov.add(movie1);
		mov.add(movie2);
		mov.add(movie3);
		mov.add(movie4);
		mov.add(movie5);
		mov.add(movie6);
		mov.add(movie7);
		mov.add(movie8);
		mov.add(movie9);
		mov.add(movie10);
		mov.add(movie11);
		mov.add(movie12);
		mov.add(movie13);
		mov.add(movie14);
		mov.add(movie15);
		mov.add(movie16);
		mov.add(movie17);
		mov.add(movie18);
		mov.add(movie19);
		mov.add(movie20);
		mov.add(movie21);
		mov.add(movie22);
		mov.add(movie23);
		mov.add(movie24);
		mov.add(movie25);
		mov.add(movie26);
		mov.add(movie27);
		mov.add(movie28);
		mov.add(movie29);
		mov.add(movie30);
		mov.add(movie31);
		mov.add(movie32);
		mov.add(movie33);
		mov.add(movie34);
		mov.add(movie35);
		mov.add(movie36);
		mov.add(movie37);
		mov.add(movie38);
		mov.add(movie39);
		mov.add(movie40);
		mov.add(movie41);
		mov.add(movie42);
		mov.add(movie43);
		mov.add(movie44);
		mov.add(movie45);
		mov.add(movie46);
		mov.add(movie47);
		mov.add(movie48);
		mov.add(movie49);
		mov.add(movie50);
		mov.add(movie51);
		mov.add(movie52);
		mov.add(movie53);
		mov.add(movie54);
		mov.add(movie55);
		mov.add(movie57);
		mov.add(movie58);
		mov.add(movie59);
		mov.add(movie60);
		Iterator<String> d= mov.iterator();
		while(d.hasNext()) {
			System.out.println(d.next());
		}
		mov.remove(movie30);
		System.out.println(mov);
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
		
		String webSeries1="the family man";
		String webSeries2="scam";
		String webSeries3="Bandish Bandits";
		String webSeries4="Panchayat ";
		String webSeries5="Paatal Lok";
		String webSeries6="mirzapur";
		String webSeries7="kota factory";
		String webSeries8="Special Ops";
		String webSeries9="";
		String webSeries10="";
		String webSeries11="aarya";
		String webSeries12="";
		String webSeries13="breath into shadow";
		String webSeries14="";
		String webSeries15=" Bang Baaja Baarat";
		String webSeries16="";
		String webSeries17="";
		String webSeries18="delhi crime";
		String webSeries19="";
		String webSeries20="";
		String webSeries21="raikar case";
		String webSeries22="";
		String webSeries23="";
		String webSeries24="";
		String webSeries25="";
		String webSeries26=" Engineering Girls ";
		String webSeries27="";
		String webSeries28="";
		String webSeries29=" Hostages ";
		String webSeries30="";
		String webSeries31=" Stories By Rabindranath Tagore";
		String webSeries32="";
		String webSeries33=" Twisted";
		String webSeries34="";
		String webSeries35="scared games";
		String webSeries36="";
		String webSeries37="";
		String webSeries38="";
		String webSeries39="made in heaven";
		String webSeries40="";
		String webSeries41="god father";
		String webSeries42="coco";
		String webSeries43="";
		String webSeries44="";
		String webSeries45="";
		String webSeries46=". F.L.A.M.E.S";
		String webSeries47="Gullak";
		String webSeries48="";
		String webSeries49="Inside Edge";
		String webSeries50="";
		String webSeries51="logan";
		String webSeries52=" Class of 2017";
		String webSeries53="";
		String webSeries54="special oops";
		String webSeries55="";
		String webSeries56="Ghoul";
		String webSeries57="";
		String webSeries58="";
		String webSeries59="Kaafir ";
		String webSeries60="Yeh Hai Meri Family ";	
		
		Collection web = new ArrayList();
		
		web.add(webSeries1);
		web.add(webSeries2);
		web.add(webSeries3);
		web.add(webSeries4);
		web.add(webSeries5);
		web.add(webSeries6);
		web.add(webSeries7);
		web.add(webSeries8);
		web.add(webSeries9);
		web.add(webSeries10);
		web.add(webSeries11);
		web.add(webSeries12);
		web.add(webSeries13);
		web.add(webSeries14);
		web.add(webSeries16);
		web.add(webSeries16);
		web.add(webSeries17);
		web.add(webSeries18);
		web.add(webSeries18);
		web.add(webSeries19);
		web.add(webSeries20);
		web.add(webSeries21);
		web.add(webSeries22);
		web.add(webSeries23);
		web.add(webSeries24);
		web.add(webSeries25);
		web.add(webSeries26);
		web.add(webSeries27);
		web.add(webSeries28);
		web.add(webSeries29);
		web.add(webSeries30);
		web.add(webSeries31);
		web.add(webSeries32);
		web.add(webSeries33);
		web.add(webSeries34);
		web.add(webSeries35);
		web.add(webSeries36);
		web.add(webSeries37);
		web.add(webSeries38);
		web.add(webSeries39);
		web.add(webSeries40);
		web.add(webSeries41);
		web.add(webSeries42);
		web.add(webSeries43);
		web.add(webSeries44);
		web.add(webSeries45);
		web.add(webSeries46);
		web.add(webSeries47);
		web.add(webSeries48);
		web.add(webSeries49);
		web.add(webSeries50);
		web.add(webSeries51);
		web.add(webSeries52);
		web.add(webSeries53);
		web.add(webSeries54);
		web.add(webSeries55);
		web.add(webSeries56);
		web.add(webSeries57);
		web.add(webSeries58);
		web.add(webSeries59);
		web.add(webSeries60);
		
		Iterator<String> w= web.iterator();
		while(w.hasNext()) {
			System.out.println(w.next());
		}
		web.remove(webSeries30);
		System.out.println(web);
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
		
		
		String cites1 = "bangalore";
		String cites2 = "bellary";
		String cites3 = "bidar";
		String cites4 = "gulbarga";
		String cites5 = "gao";
		String cites6 = "mumbai";		
		String cites7 = "delhi";
		String cites8 = "agra";		
		String cites9 = "rajastan";	
		String cites10 = "hariyana";		
		String cites11 = "bihar";
		String cites12 = "patna";
		String cites13 = "kanyakumari";
		String cites14 = "chennai";
		String cites15 = "kerala";
		String cites16 = "pondicherry";
		String cites17 = "mangalore";
		String cites18 = "karvar";
		String cites19 = "udupi";
		String cites20 = "hubli";
		String cites21 = "dharwad";
		String cites22 = "belgum";
		String cites23 = "pune";
		String cites24 = "shivmogga";
		String cites25 = "shirshi";
		String cites26 = "hydrabad";
		String cites27 = "gogak";
		String cites28 = "madyapradesh";
		String cites29 = "hospet";
		String cites30 = "sandur";
		String cites31 = "mandya";
		String cites32 = "kudligi";
		String cites33 = "";
		String cites34 = "hampi";
		String cites35 = "havri";
		String cites36 = "kota";
		String cites37 = "vishkapatnam";
		String cites38 = "nellueru";
		String cites39 = "dharmavaram";
		String cites40 = "maldives";
		String cites41 = "raajamendri";
		String cites42 = "";
		String cites43 = "karnoor";
		String cites44 = "";
		String cites45 = "adoni";
		String cites46 = "";
		String cites47 = "noida";
		String cites48 = "lucknow";
		String cites49 = "merat";
		String cites50 = "gujrat";
		String cites51 = "ahamdabad";
		String cites52 = "chicago";
		String cites53 = "paris";
		String cites54 = "london";
		String cites55 = "newyork";
		String cites56 = "assam";
		String cites57 = "ooty";
		String cites58 = "thricura";
		String cites59 = "trivendram";
		String cites60 = "kochi";
		
	Collection city= new ArrayList();
	city.add(cites1);
	city.add(cites2);
	city.add(cites3);
	city.add(cites4);
	city.add(cites5);
	city.add(cites6);
	city.add(cites7);
	city.add(cites8);
	city.add(cites9);
	city.add(cites10);
	city.add(cites11);
	city.add(cites12);
	city.add(cites13);
	city.add(cites14);
	city.add(cites15);
	city.add(cites16);
	city.add(cites17);
	city.add(cites18);
	city.add(cites19);
	city.add(cites20);
	city.add(cites21);
	city.add(cites22);
	city.add(cites23);
	city.add(cites24);
	city.add(cites25);
	city.add(cites26);
	city.add(cites27);
	city.add(cites28);
	city.add(cites29);
	city.add(cites30);
	city.add(cites31);
	city.add(cites32);
	city.add(cites33);
	city.add(cites34);
	city.add(cites35);
	city.add(cites36);
	city.add(cites37);
	city.add(cites38);
	city.add(cites39);
	city.add(cites40);
	city.add(cites41);
	city.add(cites42);
	city.add(cites43);
	city.add(cites44);
	city.add(cites45);
	city.add(cites46);
	city.add(cites47);
	city.add(cites48);
	city.add(cites49);
	city.add(cites50);
	city.add(cites51);
	city.add(cites52);
	city.add(cites53);
	city.add(cites54);
	city.add(cites55);
	city.add(cites56);
	city.add(cites57);
	city.add(cites58);
	city.add(cites59);
	city.add(cites60);
	
	Iterator<String> ci = city.iterator();
	while(ci.hasNext()) {
		System.out.println(ci.next());
	}
	city.remove(cites30);
	System.out.println(city);
	System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
	
	String car1 ="lamrogini";
	String car2 ="porch";
	String car3 ="swift";
	String car4 ="boolero";
	String car5 ="ferrari";
	String car6 ="jagur";
	String car7 ="santro";
	String car8 ="maruti";
	String car9 ="caiz";
	String car10 ="alto";
	String car11="duster";
	String car12 ="verna";
	String car13 ="city";
	String car14 ="";
	String car15 ="ranger rover";
	String car16 ="safari";
	String car17 ="marcidies benz";
	String car18 ="ford";
	String car19 ="figo";
	String car20 ="carlos";
	String car21 ="fortuner";
	String car22 ="balleno";
	String car23 ="";
	String car24 ="skoda";
	String car25 ="land rover";
	String car26 ="";
	String car27 ="missan";
	String car28 ="datsun";
	String car29 ="audi";
	String car30 ="pachero";
	String car31 ="";
	String car32 ="khushaq";
	String car33 ="glanza";
	String car34 ="";
	String car35 ="harrier";
	String car36 ="";
	String car37 ="thar";
	String car38 ="";
	String car39 ="";
	String car40 ="";
	String car41 ="";
	String car42 ="MG motor";
	String car43 ="";
	String car44 ="";
	String car45 ="mahindra xuv";
	String car46 ="kia seltos";
	String car47 ="";
	String car48 ="";
	String car49 ="kwid";
	String car50 ="";
	String car51 ="kiger";
	String car52 ="";
	String car53 ="kona";
	String car54 ="";
	String car55 ="taigo";
	String car56 ="";
	String car57 ="breeza";
	String car58 ="urban cruser";	
	String car59 ="";
	String car60 ="creta";
	
	Collection car= new ArrayList();
	car.add(car1);
	car.add(car2);
	car.add(car3);
	car.add(car4);
	car.add(car5);
	car.add(car6);
	car.add(car7);
	car.add(car8);
	car.add(car9);
	car.add(car10);
	car.add(car11);
	car.add(car12);
	car.add(car13);
	car.add(car14);
	car.add(car15);
	car.add(car16);
	car.add(car17);
	car.add(car18);
	car.add(car19);
	car.add(car20);
	car.add(car21);
	car.add(car22);
	car.add(car23);
	car.add(car24);
	car.add(car25);
	car.add(car26);
	car.add(car27);
	car.add(car28);
	car.add(car29);
	car.add(car30);
	car.add(car31);
	car.add(car32);
	car.add(car33);
	car.add(car34);
	car.add(car35);
	car.add(car36);
	car.add(car37);
	car.add(car38);
	car.add(car39);
	car.add(car40);
	car.add(car41);
	car.add(car42);
	car.add(car43);
	car.add(car44);
	car.add(car45);
	car.add(car46);
	car.add(car47);
	car.add(car48);
	car.add(car49);
	car.add(car50);
	car.add(car51);
	car.add(car52);
	car.add(car53);
	car.add(car54);
	car.add(car55);
	car.add(car56);
	car.add(car57);
	car.add(car58);
	car.add(car59);
	car.add(car60);
	
	Iterator<String> ca= car.iterator();
	while(ca.hasNext()) {
		System.out.println(ca.next());
	}
	car.remove(car30);
	System.out.println(car);
	System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
	
	String sweet1 = "goolab jamun";
	String sweet2 = "mishra pedha";
	String sweet3 = "ras malayi";
	String sweet4 = "boondi";
	String sweet5 = "chamcham";
	String sweet6 = "raasgulla";
	String sweet7 = "amarti";
	String sweet8= "jaleebi";
	String sweet9 = "kaju katli";
	String sweet10 = "moti chur laddu";
	String sweet11= "kulfi";
	String sweet12 = "jaangir";
	String sweet13 = "malpuri pheta";
	String sweet14 = "pongal";
	String sweet15 = "rabdi";
	String sweet16 = "kheer";
	String sweet17 = "sheera";
	String sweet18 = "nanakhatai";
	String sweet19 = "barfi";
	String sweet20 = "soonpapdi";
	String sweet21 = "";
	String sweet22 = "moodak";
	String sweet23 = "";
	String sweet24 = "halva";
	String sweet25 = "";
	String sweet26 = "peda";
	String sweet27 = "";
	String sweet28 = "baas sundi";
	String sweet29 = "";
	String sweet30 = "";
	String sweet31 = "kesri baat";
	String sweet32 = "";
	String sweet33 = "";
	String sweet34 = "sandesh";
	String sweet35 = "";
	String sweet36 = "coconut barfi";
	String sweet37 = "";
	String sweet38 = "sivvanyya";
	String sweet39 = "";
	String sweet40 = "";
	String sweet41 = "rasabali";
	String sweet42 = "ledikeniu";
	String sweet43 = "ada";
	String sweet44 = "rasgulla";
	String sweet45 = "puri khaja";
	String sweet46 = "gavvalu";
	String sweet47 = "";
	String sweet48 = "rabdi";
	String sweet49 = "chikki";
	String sweet50 = "";
	String sweet51 = "sonpapdi";
	String sweet52 = "rasmalai";
	String sweet53 = "phirni";
	String sweet54 = "";
	String sweet55 = "cheena gaja";
	String sweet56 = "chamcham";
	String sweet57 = "";
	String sweet58 = "cheena poda";
	String sweet59 = "";
	String sweet60 = "amirti";
	
	Collection sweet= new ArrayList();
	sweet.add(sweet1);
	sweet.add(sweet2);
	sweet.add(sweet3);
	sweet.add(sweet4);
	sweet.add(sweet5);
	sweet.add(sweet6);
	sweet.add(sweet7);
	sweet.add(sweet8);
	sweet.add(sweet9);
	sweet.add(sweet10);
	sweet.add(sweet11);
	sweet.add(sweet12);
	sweet.add(sweet13);
	sweet.add(sweet14);
	sweet.add(sweet15);
	sweet.add(sweet16);
	sweet.add(sweet17);
	sweet.add(sweet18);
	sweet.add(sweet19);
	sweet.add(sweet20);
	sweet.add(sweet21);
	sweet.add(sweet22);
	sweet.add(sweet23);
	sweet.add(sweet24);
	sweet.add(sweet25);
	sweet.add(sweet26);
	sweet.add(sweet27);
	sweet.add(sweet28);
	sweet.add(sweet29);
	sweet.add(sweet30);
	sweet.add(sweet31);
	sweet.add(sweet32);
	sweet.add(sweet33);
	sweet.add(sweet34);
	sweet.add(sweet35);
	sweet.add(sweet36);
	sweet.add(sweet37);
	sweet.add(sweet38);
	sweet.add(sweet39);
	sweet.add(sweet40);
	sweet.add(sweet41);
	sweet.add(sweet42);
	sweet.add(sweet43);
	sweet.add(sweet44);
	sweet.add(sweet45);
	sweet.add(sweet46);
	sweet.add(sweet47);
	sweet.add(sweet48);
	sweet.add(sweet49);
	sweet.add(sweet50);
	sweet.add(sweet51);
	sweet.add(sweet52);
	sweet.add(sweet53);
	sweet.add(sweet54);
	sweet.add(sweet55);
	sweet.add(sweet56);
	sweet.add(sweet57);
	sweet.add(sweet58);
	sweet.add(sweet59);
	sweet.add(sweet60);
	
	Iterator<String> swee= sweet.iterator();
	while(swee.hasNext()) {
		System.out.println(swee.next());
	}
	sweet.remove(sweet30);
	System.out.println(sweet);
	System.out.println("~~~~~~~~~~~~~~~~~~~~~~~");
	}
	

}
